name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.3
        with:
          versionSpec: '6.x'

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Zip Release
        run: zip -x '*.git*' -r release.zip . 

      - name: Get VERSION from File
        id: version_file
        run: |
          VERSION="$(cat ./VERSION)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.0.3
        with:
          overrideConfig: |
            update-build-number=false
            next-version=${{ env.VERSION }}

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v3.0.3
        with:
          versionSpec: '0.18.x'

      - uses: gittools/actions/gitreleasemanager/create@v3.0.3
        name: Create release with GitReleaseManager
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: 'jenciso'
          repository: ${{ github.repository }}
          milestone: ${{ env.VERSION }}
          name: v${{ env.VERSION }}
          assets: |
            release.zip

      - uses: gittools/actions/gitreleasemanager/publish@v3.0.3
        name: Publish release with GitReleaseManager
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: 'jenciso'
          repository: ${{ github.repository }}
          milestone: ${{ env.VERSION }}

      - uses: gittools/actions/gitreleasemanager/close@v3.0.3
        name: Close release with GitReleaseManager
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: 'jenciso'
          repository: ${{ github.repository }}
          milestone: ${{ env.VERSION }}
